CREATE TABLE BOARD(
IDX NUMBER,
TITLE VARCHAR2(200) ,
WRITER VARCHAR2(20),
REGDATE VARCHAR2(20),
COUNT NUMBER ,
CONTENT CLOB,
PRIMARY KEY(IDX)

)

;


select * from board;
select board
delete board
where idx >= 2

CREATE SEQUENCE  "BOARD_SEQ"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1

select board_seq.currval from dual
